Ajustes en el Header y en la seccion Categorias
softiReds/ProyectoCorabastos pull request #14
Opened 2024-11-22 01:35 UTC by Kafstinolli

1. Ajuste en la sección de categorías: se relacionan nombres de categorías con el menú y se insertan imágenes correspondientes.
2. Ajuste final del header: eliminación de botones innecesarios y ajuste del tamaño de la barra de búsqueda.
3. Ajuste final de la sección de categorías: se añaden imágenes, se organizan elementos y se documentan las secciones corregidas.

2024-11-22 22:32 UTC, softiReds requested changes
Resolver comentarios

2024-11-22 22:32 UTC, softiReds commented on Frontend/index.html
> +    <!-- Importacion e iconos para el menu -->
No se entiende el comentario

2024-11-22 22:32 UTC, softiReds commented on Frontend/index.html
> +      <!-- Menu -->
¿Qué menú?

2024-11-23 14:35 UTC, Kafstinolli commented on Frontend/index.html
> +    <!-- Importacion e iconos para el menu -->
se detalla mas a fondo el comentario: "Definición de íconos SVG para cada categoría utilizada en el menú desplegable"

2024-11-23 14:37 UTC, Kafstinolli commented on Frontend/index.html
> +      <!-- Menu -->
Menú desplegable de navegación principal con categorías e íconos SVG

2024-11-23 16:45 UTC, softiReds approved these changes
Aprobado

2024-11-24 12:08 UTC, JUANEScat2022 approved these changes
Aprobado por shayan

2024-11-26 02:22 UTC, merged