Se realiza estructura inicial del login, se agregan alertas funcional…
softiReds/ProyectoCorabastos pull request #15
Opened 2024-11-22 02:18 UTC by JUANEScat2022

…es e interactuvas en la parte inicial de la pagina

2024-11-22 22:30 UTC, softiReds requested changes
Resolver comentarios

2024-11-22 22:30 UTC, softiReds commented on Frontend/loginUser.html
> +    <style>
Crear archivo .css para los estilos

2024-11-26 00:06 UTC, softiReds approved these changes
Resolver comentarios

2024-11-26 20:12 UTC, Kafstinolli commented
Por favor los archivos html crearlos dentro de la carpeta html

2024-11-26 20:13 UTC, Kafstinolli approved these changes

2024-11-26 20:13 UTC, merged